{% set name = "Qt.py" %}
{% set version = "2.0.1" %}
{% set sha256 = "5718008211782e4d7a058662029709f72506a2b7164f70de432d0ae1f0f97c76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qt_py-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pyside2
  imports:
    - Qt

about:
  home: http://github.com/mottosso/Qt.py
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Minimal Python 2 & 3 shim around all Qt bindings - PySide, PySide2, PyQt4 and PyQt5.

extra:
  recipe-maintainers:
    - fredrikaverpil
    - mottosso
