{% set name = "Qt.py" %}
{% set version = "1.1.0" %}
{% set sha256 = "866d0c0307631cfac4f33829806549a3f208fdbfc9c02fabf2277d1ab2d80e93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pyside2
  imports:
    - Qt

about:
  home: http://github.com/mottosso/Qt.py
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Minimal Python 2 & 3 shim around all Qt bindings - PySide, PySide2, PyQt4 and PyQt5.'

extra:
  recipe-maintainers:
    - fredrikaverpil
    - mottosso
